"""Initial migration

Revision ID: 9219ef2b623e
Revises: 
Create Date: 2025-11-10 14:13:23.137624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9219ef2b623e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('team_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_solution_id'), 'fantasy_solution', ['id'], unique=False)
    op.create_table('sim_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('seasons', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_runs_id'), 'sim_runs', ['id'], unique=False)
    op.create_table('agg_team_season',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('nrr', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'season'),
    sa.UniqueConstraint('team_id', 'season', name='uq_agg_team_season')
    )
    op.create_table('sim_team_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('title_p', sa.Float(), nullable=False),
    sa.Column('finals_p', sa.Float(), nullable=False),
    sa.Column('playoffs_p', sa.Float(), nullable=False),
    sa.Column('exp_wins', sa.Float(), nullable=False),
    sa.Column('nrr_p10', sa.Float(), nullable=True),
    sa.Column('nrr_p50', sa.Float(), nullable=True),
    sa.Column('nrr_p90', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['sim_runs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sim_team_summary_run_id', 'sim_team_summary', ['run_id'], unique=False)
    op.create_index(op.f('ix_sim_team_summary_id'), 'sim_team_summary', ['id'], unique=False)
    op.create_index(op.f('ix_sim_team_summary_run_id'), 'sim_team_summary', ['run_id'], unique=False)
    op.create_table('agg_player_season',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('sr', sa.Float(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('wickets', sa.Integer(), nullable=True),
    sa.Column('econ', sa.Float(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season'),
    sa.UniqueConstraint('player_id', 'season', name='uq_agg_player_season')
    )
    op.create_table('fantasy_projection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('expected_points', sa.Float(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=True),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fantasy_projection_matchday', 'fantasy_projection', ['matchday'], unique=False)
    op.create_index(op.f('ix_fantasy_projection_id'), 'fantasy_projection', ['id'], unique=False)
    op.create_index(op.f('ix_fantasy_projection_matchday'), 'fantasy_projection', ['matchday'], unique=False)
    op.create_table('sim_player_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('award_type', sa.String(), nullable=False),
    sa.Column('p_win', sa.Float(), nullable=False),
    sa.Column('exp_value', sa.Float(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=True),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.CheckConstraint("award_type IN ('orange', 'purple')", name='chk_award_type'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['sim_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sim_player_summary_run_id', 'sim_player_summary', ['run_id'], unique=False)
    op.create_index(op.f('ix_sim_player_summary_id'), 'sim_player_summary', ['id'], unique=False)
    op.create_index(op.f('ix_sim_player_summary_run_id'), 'sim_player_summary', ['run_id'], unique=False)
    op.create_table('strategy_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('innings', sa.Integer(), nullable=False),
    sa.Column('over_no', sa.Integer(), nullable=False),
    sa.Column('wickets_down', sa.Integer(), nullable=False),
    sa.Column('striker_id', sa.Integer(), nullable=True),
    sa.Column('non_striker_id', sa.Integer(), nullable=True),
    sa.Column('current_bowler_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['current_bowler_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['non_striker_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['striker_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_context_match', 'strategy_context', ['match_id', 'innings', 'over_no'], unique=False)
    op.create_index(op.f('ix_strategy_context_id'), 'strategy_context', ['id'], unique=False)
    op.create_table('strategy_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['strategy_context.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_recommendation_id'), 'strategy_recommendation', ['id'], unique=False)
    op.add_column('matches', sa.Column('date_utc', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('match_no', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('winner_team_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('margin_text', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('result', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('status', sa.String(), nullable=True))
    op.create_index('idx_matches_date_utc', 'matches', ['date_utc'], unique=False)
    op.create_foreign_key(None, 'matches', 'teams', ['winner_team_id'], ['id'])
    op.add_column('player_performances', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('player_performances', sa.Column('runs', sa.Integer(), nullable=True))
    op.add_column('player_performances', sa.Column('balls', sa.Integer(), nullable=True))
    op.add_column('player_performances', sa.Column('wickets', sa.Integer(), nullable=True))
    op.add_column('player_performances', sa.Column('overs', sa.Float(), nullable=True))
    op.add_column('player_performances', sa.Column('sr', sa.Float(), nullable=True))
    op.add_column('player_performances', sa.Column('econ', sa.Float(), nullable=True))
    op.create_index('idx_player_performances_player_id', 'player_performances', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_performances_player_id'), 'player_performances', ['player_id'], unique=False)
    op.create_foreign_key(None, 'player_performances', 'teams', ['team_id'], ['id'])
    op.add_column('players', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.alter_column('players', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('teams', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('teams', 'home_venue')
    op.add_column('venues', sa.Column('altitude_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'altitude_m')
    op.add_column('teams', sa.Column('home_venue', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('teams', 'city')
    op.alter_column('players', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('players', 'birth_date')
    op.drop_column('players', 'full_name')
    op.drop_constraint(None, 'player_performances', type_='foreignkey')
    op.drop_index(op.f('ix_player_performances_player_id'), table_name='player_performances')
    op.drop_index('idx_player_performances_player_id', table_name='player_performances')
    op.drop_column('player_performances', 'econ')
    op.drop_column('player_performances', 'sr')
    op.drop_column('player_performances', 'overs')
    op.drop_column('player_performances', 'wickets')
    op.drop_column('player_performances', 'balls')
    op.drop_column('player_performances', 'runs')
    op.drop_column('player_performances', 'team_id')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_index('idx_matches_date_utc', table_name='matches')
    op.drop_column('matches', 'status')
    op.drop_column('matches', 'result')
    op.drop_column('matches', 'margin_text')
    op.drop_column('matches', 'winner_team_id')
    op.drop_column('matches', 'match_no')
    op.drop_column('matches', 'date_utc')
    op.drop_index(op.f('ix_strategy_recommendation_id'), table_name='strategy_recommendation')
    op.drop_table('strategy_recommendation')
    op.drop_index(op.f('ix_strategy_context_id'), table_name='strategy_context')
    op.drop_index('idx_strategy_context_match', table_name='strategy_context')
    op.drop_table('strategy_context')
    op.drop_index(op.f('ix_sim_player_summary_run_id'), table_name='sim_player_summary')
    op.drop_index(op.f('ix_sim_player_summary_id'), table_name='sim_player_summary')
    op.drop_index('idx_sim_player_summary_run_id', table_name='sim_player_summary')
    op.drop_table('sim_player_summary')
    op.drop_index(op.f('ix_fantasy_projection_matchday'), table_name='fantasy_projection')
    op.drop_index(op.f('ix_fantasy_projection_id'), table_name='fantasy_projection')
    op.drop_index('idx_fantasy_projection_matchday', table_name='fantasy_projection')
    op.drop_table('fantasy_projection')
    op.drop_table('agg_player_season')
    op.drop_index(op.f('ix_sim_team_summary_run_id'), table_name='sim_team_summary')
    op.drop_index(op.f('ix_sim_team_summary_id'), table_name='sim_team_summary')
    op.drop_index('idx_sim_team_summary_run_id', table_name='sim_team_summary')
    op.drop_table('sim_team_summary')
    op.drop_table('agg_team_season')
    op.drop_index(op.f('ix_sim_runs_id'), table_name='sim_runs')
    op.drop_table('sim_runs')
    op.drop_index(op.f('ix_fantasy_solution_id'), table_name='fantasy_solution')
    op.drop_table('fantasy_solution')
    # ### end Alembic commands ###

